### ISSUE TITLE
Actions without arguments break

### ISSUE THREAD

**Issue by asakusuma** [glimmerjs/glimmer-application#34]
If there's no argument, or only string literal arguments, action function is undefined.

**Comment by asakusuma** [comment]
Looks like it may be only for actions on `a` tags

**Comment by robbiepitts** [comment]
@asakusuma Hmm, I can't seem to reproduce. Can you show your usage?

**Comment by robbiepitts** [comment]
Nm, I see in the linked PR.

**Comment by locks** [comment]
Is this still a problem?

**Comment by asakusuma** [comment]
@locks no, fixed in earlier commit
