### ISSUE TITLE
Warning when running `ember build` with `--web-component` apps

### ISSUE THREAD

**Issue by mswanson** [glimmerjs/glimmer-application#39]
When creating a Glimmer app with `--web-component` the `ember build` step throws the following warning.
```
/src/index.ts(21,26): Argument of type 'App' is not assignable to parameter of type 'Application'.
  Types of property 'env' are incompatible.
    Type 'Environment' is not assignable to type 'Environment'. Two different types with this name exist, but they are unrelated.
      Types have separate declarations of a private property 'helpers'.
```

After some cursory research with @robbiepitts it seems like the issue is that both `@glimmer/component` and `@glimmer/web-component` include `@glimmer/application` resulting in multiple instances of `Application` and `Environment`.

To be clear the app still builds and functions. In dev mode (i.e. when using `ember serve`) the warning is not present.

At first Robbie thought it might be an issue of version mismatch between the main `package.json` and the `package.json` files for `@glimmer/component` and `@glimmer/web-component`. Currently both of them request version `0.3.x` and the main package installs `0.4.0`. Updating both packages to request `0.4.0` didn't solve the issue.

**Comment by robbiepitts** [comment]
Closing in favor of https://github.com/glimmerjs/glimmer-web-component/issues/9 (since this is probably not an issue with @glimmer/application).
