### ISSUE TITLE
nested each causes endless rerender

### ISSUE THREAD

**Issue by MartinMalinda** [glimmerjs/glimmer-application#43]
If I have nested each helpers like so:

```hbs
{{#each grid key="@index" as |gridRow|}}
  {{#each gridRow key="@index" as |gridItem|}}
    <grid-item />
  {{/each}}
{{/each}}
```
I can see endless re-renders in the timeline. Not sure if this is WAI.

Maybe it can happen with single each as well. (cc @gavinjoyce)

Simple reproduction repo is here: https://github.com/MartinMalinda/glimmer-endless-render

**Comment by GavinJoyce** [comment]
This happens for me with a single `each`:

```ts
import Component from "@glimmer/component";

export default class MyApp extends Component {
  speakers = ['Tom', 'Yehuda', 'Ed'];
}
```

```hbs
<ul>
  {{#each speakers key="@index" as |speaker|}}
    <li>{{speaker}}</li>
  {{/each}}
</ul>
```

**Comment by GavinJoyce** [comment]
It seems that [`component.args = bucket.namedArgsSnapshot();`](https://github.com/glimmerjs/glimmer-component/blob/fbd7bfef2a5c094363932571b7a5d287212574ed/src/component-manager.ts#L114) is resulting in a `propertyDidChange`, which then causes a looped rerender

**Comment by GavinJoyce** [comment]
Related, we seem to call [`rerender`](https://github.com/glimmerjs/glimmer-application/blob/cdcfda6b386264449e7daa0f12f200b77c6931c8/src/application.ts#L149-L153) twice on boot for an app with static content

**Comment by locks** [comment]
@chadhietala I believe you were looking into some of this?

**Comment by chadhietala** [comment]
@tomdale this is what I was talking about. We need to check the global revision we schedule a re-render.

**Comment by tomdale** [comment]
@chadhietala Nope. Args is a watched property, so setting it is causing it to rerender. It also means the current revision is getting bumped. As we talked about. 😉

**Comment by tomdale** [comment]
This is a weird case because we want `args` to invalidate other tracked properties, but not schedule a rerender.

**Comment by CvX** [comment]
@tomdale Is there anything that has to be done beyond removing args tracking?
I did that and added a test for the rerender loop (https://github.com/CvX/glimmer-component/commit/13456a919f95c23e485f12656153b315b6610fa2).
All tests pass, but maybe there are some other args-related functionalities that were never tested?
I'd really like to squash this bug. 😃

**Comment by balinterdi** [comment]
@tomdale To clarify, we currently have to do `@tracked('args')` as we cannot track individual attributes, like `@tracked('args.rating')`, right? (I tried that and it didn't work but perhaps I was missing something?)

**Comment by CvX** [comment]
@balinterdi You're completely right, forgot about that use case.
Updated the test and added dirtying the args tag. https://github.com/CvX/glimmer-component/commit/a8aaa2b435d1d133a0d3cf930077e077fa643a96

**Comment by balinterdi** [comment]
@CvX Does it work now? It's still a workaround, though, isn't it? (And we should be able to track individual properties.)

**Comment by CvX** [comment]
@balinterdi it does its job, but whether it should land on master in this form is a question for someone with more (ie. any 😁) experience with glimmer code.

Don't know what's the plan for tracking individual properties.

**Comment by locks** [comment]
This repo has been merged with [glimmerjs/glimmer.js](https://github.com/glimmerjs/glimmer.js) (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
