### ISSUE TITLE
Can't create new glimmer app - Unknown blueprint

### ISSUE THREAD

**Issue by balinterdi** [glimmerjs/glimmer-application#44]
I followed the instructions on the website but got stuck at the step of creating a new application:

    $ ember new glimmer-stars -b @glimmer/blueprint
    Unknown blueprint: @glimmer/blueprint

I tried using the full repo URL for the blueprint (`https://github.com/glimmerjs/glimmer-application.git`, not sure if that's the right one), but then received another error:

    $ ember new glimmer-stars -b https://github.com/glimmerjs/glimmer-application.git
    installing ember-cli117231-19812-1s8ldo3.i968lx47vi
    WARNING: Skipping npm install: package.json not found
    Error creating new application. Removing generated directory `./glimmer-stars`

**Comment by mattmarcum** [comment]
I couldn't get that to work (i.e. `-b @glimmer/blueprint`) until I got ember-cli upgraded to 2.13.0-beta.2

**Comment by locks** [comment]
@balinterdi that's not the right GitHub repository, the blueprint is [glimmer-blueprint](https://github.com/glimmerjs/glimmer-blueprint/) ;) If you did `yarn global add`, be sure to remove the npm `ember-cli`, as it could also be interfering.

As we explain in at the bottom of https://glimmerjs.com/guides/installing, you currently need to install the canary version of Ember CLI so that the npm blueprint experiment is enabled.
Ember CLI doesn't have the concept of canary versioning because it's the latest commit on the master branch at a given time, that's why it shows `-beta`.

Please reopen if the information provided does not solve your situation, thank you!

**Comment by balinterdi** [comment]
@locks Thank you for your prompt reply.

I uninstalled the npm ember (npm uninstall -g ember) but now I don't have an ember command although I've done `yarn global add ember-cli/ember-cli`. I must be missing something.

**Comment by locks** [comment]
@balinterdi apparently some of the `yarn` installers don't set up the path properly :\ I have fallen back to `npm install -g` myself. Can you open a separate issue? I think we want to address this explicitly in the installation guide.

**Comment by mattmarcum** [comment]
I found this command works to use yarn to install globally:

```bash
yarn global add ember-cli/ember-cli  --global-folder `npm config get prefix`
```

That works for me on my system where I'm using `nvm` to manage my node version

**Comment by balinterdi** [comment]
Thank you. After installing the canary version of ember-cli, I could create a new glimmer project by issuing:

    $ ember new glimmer-stars -b https://github.com/glimmerjs/glimmer-blueprint.git

It didn't, however, worked with 

    $ ember new hello-glimmer -b @glimmer/blueprint 

, I received the same `Unknown blueprint` error.

Will create a separate issue for the yarn issue as requested but I now have to board my plane :)

**Comment by balinterdi** [comment]
Oh, spoke too early, towards the end of the installation process I got this:

```
Caching binary to /Users/balint/.npm/node-sass/3.13.1/darwin-x64-48_binding.node
Installing packages for tooling via npm.Binary found at /Users/balint/code/balinterdi/emberjs/glimmer-stars/node_modules/@glimmer/application-pipeline/node_modules/broccoli-sass/node_modules/node-sass/vendor/darwin-x64-48/binding.node
Testing binary
Binary is fine
Installed packages for tooling via npm.
No bower.json present
Error: No bower.json present
    at createError (/usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/util/createError.js:4:15)
    at /usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/core/Project.js:49:19
    at /usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/node_modules/q/q.js:1229:26
    at _fulfilled (/usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/ember-cli/node_modules/bower/lib/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
ember new glimmer-stars -b https://github.com/glimmerjs/glimmer-blueprint.git  119.93s user 60.82s system 121% cpu 2:29.26 total
```

It does not seem like a critical error, though, the project is created just fine, afaict.

**Comment by locks** [comment]
_bower_? :thinking: let's talk on Slack afterwards, have a safe flight!

**Comment by balinterdi** [comment]
This was resolved and the bower dependency turned out to be my fault, result of not using Ember CLI Canary. What led me astray was that in [the README of glimmer-blueprint](https://github.com/glimmerjs/glimmer-blueprint) it seemed like it was sufficient to say (`npm install -g ember-cli/ember-cli to install Ember CLI Canary).

After really installing the canary version, `ember new glimmer-stars -b @glimmer/blueprint` worked just fine (though I wonder if there shouldn't be an `app` folder in the newly created app, the [glimmer.js guides](https://glimmerjs.com/guides/filesystem-layout) make it seem so).

@locks Thank you for your help. Should I create issues/PRs for the above mentioned inaccuracies?
