### ISSUE TITLE
Require wrapping for user land helpers.

### ISSUE THREAD

**Issue by rwjblue** [glimmerjs/glimmer-application#47]
Similar conceptually to what is done in Ember-land all userland helpers should be wrapped or decorated. This allows us to incrementally improve/change/etc the helper API and provide compatibility with existing helpers.

Possible API's:

---

Similar to Ember's:

```js
import { buildHelper } from '@glimmer/application';

export default buildHelper(function() {

})
```

---

Decorator specific:

```js
import { helper } from '@glimmer/application';

export default @helper function() {

}
```

---

Other?

**Comment by locks** [comment]
This repo has been merged with [glimmerjs/glimmer.js](https://github.com/glimmerjs/glimmer.js) (into a monorepo setup). An RFC might be more applicable here.

Sorry for the noise, but thank you for your help!
