### ISSUE TITLE
Strange errors after running `ember serve`

### ISSUE THREAD

**Issue by lbaillie** [glimmerjs/glimmer-application#48]
Below is the actual error @vaidehijoshi and I saw after running `ember serve` on a brand new Glimmer project. It otherwise builds fine, but thought you might want to know:

```
ember s
/src/index.ts(21,26): Argument of type 'App' is not assignable to parameter of type 'Application'.
  Types of property 'env' are incompatible.
    Type 'Environment' is not assignable to type 'Environment'. Two different types with this name exist, but they are unrelated.
      Types have separate declarations of a private property 'helpers'.
Livereload server on http://localhost:49153
Serving on http://localhost:4200/

Build successful - 3955ms.
```

Happy to provide any other information that might be helpful!

**Comment by robbiepitts** [comment]
Thanks for reporting this! It is safe to ignore. It's just a TS warning and is probably the fault of @glimmer/web-component, where we already have an [issue](https://github.com/glimmerjs/glimmer-web-component/issues/9) open for this. Unfortunately I have not yet cracked this nut (haven't worked on it a whole lot yet though tbh).

**Comment by locks** [comment]
@robbiepitts we might want to leave one of these open so people can find it and we can reference back?

**Comment by robbiepitts** [comment]
@locks Yeah, https://github.com/glimmerjs/glimmer-web-component/issues/9 is open still.

**Comment by robbiepitts** [comment]
Oh, but leave one in @glimmer/application open you mean?

**Comment by locks** [comment]
@robbiepitts na, I think that's probably the best course of action.
Thanks for giving this a go @lbaillie and @vaidehijoshi 😁
