### ISSUE TITLE
Document (and improve) using npm packages

### ISSUE THREAD

**Issue by wycats** [glimmerjs/glimmer-application#57]
The first step would be to document the current status.

A further step would be to make it more seamless out of the box.

@rwjblue @tomdale Can you chime in with some discussion on what "it just works" would mean here?

I think there's some conflict between Webpack's "make CJS just work" philosophy and rollup's "try to be more conservative and force you to be precise about what CJS integration means" philosophy. We should try to make things work as well as people across the ecosystem expect them to.

**Comment by rwjblue** [comment]
> Can you chime in with some discussion on what "it just works" would mean here?

Currently, things "just work" for packages that have either a `modules` or `jsnext:main` entry point.

> I think there's some conflict between Webpack's "make CJS just work" philosophy and rollup's "try to be more conservative and force you to be precise about what CJS integration means" philosophy. 

Confirm.  It is now possible to opt-in to CJS support, and that is documented in [the glimmer/application-pipeline README](https://github.com/glimmerjs/glimmer-application-pipeline#importing-commonjs-modules).

**Comment by tpitale** [comment]
Can there be documentation for how to use application-pipeline in other "build tools" (e.g., Rails adding Webpack)? Much discussion in https://github.com/glimmerjs/glimmer-vm/issues/448

**Comment by locks** [comment]
This repo has been merged with [glimmerjs/glimmer.js](https://github.com/glimmerjs/glimmer.js) (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
