### ISSUE TITLE
Main component JS ignored

### ISSUE THREAD

**Issue by asakusuma** [glimmerjs/glimmer-application#7]
Tried adding a backing js component to the main component. It seems to be ignored. I'm guessing the component needs to be created in [`application.render()`](https://github.com/glimmerjs/glimmer-application/blob/master/src/application.ts#L82-L92)?

Repro `hello-world` branch: https://github.com/asakusuma/hello-glimmer/tree/main-component-bug

**Comment by robbiepitts** [comment]
Yeah, that's not a thing, at least right now. The entry point is merely a template–without a backing component class–where you would invoke your root component.

**Comment by asakusuma** [comment]
I see, good to know, thanks.
