### ISSUE TITLE
Docs lacking: how do I use Glimmer as a view layer for my app?

### ISSUE THREAD

**Issue by cfv1984** [glimmerjs/glimmer-application#82]
I've been looking for a good component library that isn't React. Glimmer tickles me in all the right places, but I cannot figure out how to just require it instead of bringing the ember-cli and the rest of the jungle along. 

Is that something that is possible? Is it documented anywhere? I'm guessing it should be in the docs for this and probably the original site too.

**Comment by locks** [comment]
You cannot just import it at this point. You can develop the Glimmer components using Ember CLI and then [integrate them in your website using custom elements](https://glimmerjs.com/guides/using-glimmer-as-web-components). That is what we're doing in the website with https://github.com/ember-learn/glimmer-styleguide/.

I'm closing the issue as I hope I've answered you, unfortunately in the negative. I hope you still follow the project, and use it somehow :) If you want to discuss specific strategies, I suggest the Ember slack, there's a glimmer-dedicated room.

Thanks for giving Glimmer a go!
