### ISSUE TITLE
each helper attempts to render extraneous components

### ISSUE THREAD

**Issue by asakusuma** [glimmerjs/glimmer-application#9]
After applying https://github.com/glimmerjs/glimmer-application/pull/8, `each` loops that render components are rendering an extra iteration and throwing an error.

![screenshot](https://i.imgsafe.org/7adfd9a18a.png)

**Comment by robbiepitts** [comment]
And this renders correctly:

```hbs
<ul>
  {{#each names key="@index" as |name|}}
    <li>{{name}}</li>
  {{/each}}
</ul>
```

**Comment by asakusuma** [comment]
Yep, iterating works over an array of primitives fine for me too.

**Comment by asakusuma** [comment]
Forgot to post my repro commit to `hello-ember`

https://github.com/asakusuma/hello-glimmer/commit/515fb43df641b4943a1b7fa1cc17cde0c142fb49

**Comment by asakusuma** [comment]
Doing some opcode snooping. `OpenComponent` is getting called the correct number of times, with `EnterList` and `ExitList` getting called. The `HelloWorld` component constructor is only called 4 times as expected. The last 3 opcodes before the error are `DidRenderLayout > CloseComponent > Text`. The [`Text`](https://github.com/tildeio/glimmer/blob/1759c16defc546b034b97e37141187652ed93859/packages/%40glimmer/runtime/lib/compiled/opcodes/dom.ts#L26-L28) opcode is where the error is thrown. Which seems to be the source of the last `hello-world` element.

**Comment by asakusuma** [comment]
I modified the repro commit to be super simple. There's now no text outside of the `hello-world` component, and the only name in `names` is  "Tom." I'm not super familiar with the opcode ecosystem, but the opcodes for this specific execution seem suspect. Since the only text is inside `hello-world`, which is inside an `each`, I wouldn't expect there to be any `Text` opcode until the `EnterList` opcode, but in fact there are two `Text` opcodes before `EnterList`.

```
PutComponent
OpenComponent
BindCallerScope
OpenComponentElement
DidCreateElement
ShadowAttributes
CloseBlock
StaticAttr
FlushElement
Text
BindNamedArgs
BindCallerScope
OpenComponentElement
DidCreateElement
ShadowAttributes
CloseBlock
StaticAttr
FlushElement
Text
EvaluatePut
DynamicContent
Text
CloseElement
Text
DidRenderLayout
PutArgs
Enter
PutIterator
JumpUnless
EnterList
NextIter
EnterWithKey
Evaluate
PushChildScope
BindPositionalArgs
Text
PutComponent
OpenComponent
BindNamedArgs
BindCallerScope
OpenComponentElement
DidCreateElement
ShadowAttributes
PushChildScope
BindPositionalArgs
PopScope
CloseBlock
StaticAttr
FlushElement
Text
EvaluatePut
DynamicContent
Text
CloseElement
Text
DidRenderLayout
CloseComponent
Text
PopScope
Exit
Jump
NextIter
ExitList
Exit
CloseElement
DidRenderLayout
CloseComponent
Text
```

**Comment by locks** [comment]
This repo has been merged with [glimmerjs/glimmer.js](https://github.com/glimmerjs/glimmer.js) (into a monorepo setup). I am not sure if this issue is still applicable, but if you could confirm it is still an ongoing concern and open it over there that would be very helpful.

Sorry for the noise, but thank you for your help!
